Third homework
Sorokintech/skypro-cardgame-project pull request #3
Opened 2022-08-04 19:26 UTC by Sorokintech

Добавил 2 и 3 экран. Пока без логической привязки к логики и динамики.

2022-08-05 06:34 UTC, mrerberg requested changes

2022-08-05 06:34 UTC, mrerberg commented on src/easy-mode.js
> +const templateEasyMode = {
Я думаю, шаблоны уровней сложности можно объединить в один файл

2022-08-05 06:34 UTC, mrerberg commented on src/script.js
> +// startButton.addEventListener('click', (event) => {
Мертвый код стоит удалять, не хранить

2022-08-05 06:34 UTC, mrerberg commented on src/script.js
> +difficultyButtons.forEach((button) => {
Можно попробовать реализовать через https://learn.javascript.ru/event-bubbling

2022-08-14 14:36 UTC, Sorokintech commented on src/easy-mode.js
> +const templateEasyMode = {
Готово

2022-08-14 14:36 UTC, Sorokintech commented on src/script.js
> +// startButton.addEventListener('click', (event) => {
Готово

2022-08-14 14:37 UTC, Sorokintech commented on src/script.js
> +difficultyButtons.forEach((button) => {
Вот тут почитал, попробовал, видимо пока не заходит в голову, либо прошу отложить на потом, либо Миша пожалуйста подсказку)

2022-08-14 20:40 UTC, yadimko approved these changes
Получается супер)

2022-08-14 20:40 UTC, yadimko commented on dist/bundle.js
> +  const t = document.querySelector('.app');
в идеале надо придумать более понятный нейминг
не факт что через месяц ты сам вспомнишь что к чему)

2022-08-14 20:40 UTC, yadimko commented on src/script.js
> +  if (chosenDifficulty === '1') {
сможешь сделать через switch - case?

2022-08-14 20:40 UTC, yadimko commented on src/script.js
> +  1: './src/cards/clubs/jack.png',
будет ли удобнее такая структура для тебя?
{
  hearts: {
    king: ...,
    queen: ...,
  },
  ...остальные масти
}

и работать с элементами объекта key - values

2022-08-15 06:27 UTC, mrerberg commented on src/script.js
> +  if (chosenDifficulty === '1') {
Ради бога не нужно через switch. Эта конструкция громоздкая, if-return выглядит вполне нормально

2022-08-15 06:35 UTC, mrerberg commented on src/script.js
> +difficultyButtons.forEach((button) => {
https://codepen.io/mrerberg/pen/bGvmmKY?editors=1111

2022-08-15 06:40 UTC, mrerberg requested changes

2022-08-15 06:40 UTC, mrerberg commented on dist/bundle.js
> +  const t = document.querySelector('.app');
Папка dist не должна быть в гите, нужно ее добавить в гитигнор и удалить из пулл реквеста

2022-08-15 06:40 UTC, mrerberg commented on src/script.js
> +    app.style.height = '100vh';
Назначай лучше стили через класс, а не напрямую

2022-08-15 06:40 UTC, mrerberg commented on src/script.js
> +  } else if (chosenDifficulty === '3') {
Код из if к if практически одинаковый. Придумай, как написать обобщить код и избавиться от повторения

2022-08-15 06:40 UTC, mrerberg commented on src/script.js
> +    let currentSrc = e.src;
У тебя код идет просто сплошняком, нет вертикальных отступов между независимыми/отдельными кусками кода. Это сильно ухудшает читаемость

2022-08-15 06:40 UTC, mrerberg commented on src/script.js
> +  22: './src/cards/spades/queen.png',
./src/cards путь повторяется, в константу

2022-08-15 06:40 UTC, mrerberg commented on src/script.js
> +  25: './src/cards/spades/8.png',
Алгоритм создания карточек можно описать в виде функции и не писать пути в ручную

2022-08-15 06:40 UTC, mrerberg commented on src/script.js
> +function shuffle(array) {
helper / утилитарные функции следует вынеси в отдельные файлы, не компануй все в одном файле

2022-08-17 17:46 UTC, Sorokintech commented on src/script.js
> +  1: './src/cards/clubs/jack.png',
Вся формула выставления карт рассчитана под кол-во карт в данном объекте, все нужно ломать будет. На будущее учту.

2022-08-17 17:48 UTC, Sorokintech commented on src/script.js
> +    app.style.height = '100vh';
Готово

2022-08-17 18:07 UTC, Sorokintech commented on src/script.js
> +  } else if (chosenDifficulty === '3') {
Исправил

2022-08-17 18:17 UTC, Sorokintech commented on src/script.js
> +    let currentSrc = e.src;
Вроде поправил

2022-08-17 19:03 UTC, Sorokintech commented on src/script.js
> +  22: './src/cards/spades/queen.png',
Исправил

2022-08-17 19:07 UTC, Sorokintech commented on src/script.js
> +  25: './src/cards/spades/8.png',
Здесь речь идет о функции для пути или для создания в целом? если для создания и отображения на страницах, то нужно всю логику менять(

2022-08-17 19:15 UTC, Sorokintech commented on src/script.js
> +  22: './src/cards/spades/queen.png',
Но вернул, сломалась логика, пока нужно хвосты подчистить, потом подумаю вернусь.

2022-08-22 08:59 UTC, merged